import type { Prisma } from '@prisma/client'
import { prisma } from './db'

// UUID pattern — org IDs are always UUIDs generated by Prisma, safe to interpolate
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export async function withTenant<T>(
  organizationId: string,
  fn: (tx: Prisma.TransactionClient) => Promise<T>
): Promise<T> {
  if (!UUID_RE.test(organizationId)) {
    throw new Error(`Invalid organizationId: ${organizationId}`)
  }

  return prisma.$transaction((tx: Prisma.TransactionClient) => {
    // SET LOCAL does not support parameterised values ($1), so we use
    // $executeRawUnsafe with a validated UUID — no injection risk.
    return tx.$executeRawUnsafe(
      `SET LOCAL "app.current_tenant_id" = '${organizationId}'`
    ).then(() => fn(tx))
  })
}
