-- AlterTable
ALTER TABLE "organization_settings" ADD COLUMN     "oidcAuthorizationUrl" TEXT,
ADD COLUMN     "oidcClientId" TEXT,
ADD COLUMN     "oidcClientSecret" TEXT,
ADD COLUMN     "oidcDiscoveryUrl" TEXT,
ADD COLUMN     "oidcEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "oidcIssuer" TEXT,
ADD COLUMN     "oidcJwksUrl" TEXT,
ADD COLUMN     "oidcScope" TEXT NOT NULL DEFAULT 'openid profile email',
ADD COLUMN     "oidcTokenUrl" TEXT,
ADD COLUMN     "oidcUserinfoUrl" TEXT,
ADD COLUMN     "samlCertificate" TEXT,
ADD COLUMN     "samlEmailField" TEXT,
ADD COLUMN     "samlEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "samlEntryPoint" TEXT,
ADD COLUMN     "samlIssuer" TEXT,
ADD COLUMN     "samlNameField" TEXT,
ADD COLUMN     "samlNameIdField" TEXT,
ADD COLUMN     "samlNameIdFormat" TEXT,
ADD COLUMN     "samlPrivateKey" TEXT,
ADD COLUMN     "ssoAutoProvision" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "ssoDefaultRole" TEXT NOT NULL DEFAULT 'member',
ADD COLUMN     "ssoEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "ssoProtocol" TEXT;
